### ISSUE TITLE
response body, message is empty

### ISSUE THREAD

**Issue by ImGaram** [Diet-Management/DM_Android#5]
Response{protocol=http/1.1, code=200, message=, url=http://13.124.121.122:8081/v1/member/join}
2022-03-24 23:31:33.049 31188-31188/com.example.dietmanagement D/SUCCESS: onResponse body: {}

**Comment by HWANBINYOO** [comment]
? 이슈는 뭐하는데야

**Comment by ImGaram** [comment]
이슈는 작업의 버그 수정, 새로운 추가될 기능, 개선해야하는 기능 등등 모든 것이 될 수 있다. 모든 활동 내역에 대해 이슈를 등록하고 그 이슈를 기반으로 작업을 진행한다. 그리고 이슈를 만들면 이슈를 열었다(open)라고 하고, 작업이 끝나 이슈를 정리하면 이슈를 닫았다(close)라고 말한다. 라고 합니다
